source "https://rubygems.org"

ruby "2.6.8"

gem "fastlane", '2.172.0'

# plugins_path = File.join(File.dirname(__FILE__), 'fastlane', 'Pluginfile')
# eval_gemfile(plugins_path) if File.exist?(plugins_path)
